name: ğŸ“• Deploy headless docs
on:
    push:
        branches:
            - master
    pull_request: # TODO remove

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    pages: write
    contents: write

jobs:
    deploy:
        name: ğŸ“• Deploy headless docs
        runs-on: ubuntu-latest

        env:
            PRODUCTION_REMOTE: https://git:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ vars.DEPLOY_REPOSITORY }}

        steps:
            - name: ğŸ“¥ Checkout repo
              uses: actions/checkout@v4

            - name: âš™ï¸ Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn

            - name: âš™ï¸ Setup git
              run: |
                  echo Deploying to pages to $PRODUCTION_REMOTE
                  git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
                  git remote add production $PRODUCTION_REMOTE
                  git config --global user.email support+actions@github.com
                  git config --global user.name github-actions-bot

            - name: ğŸ“¥ Download deps
              run: yarn install --frozen-lockfile

            - name: ğŸ”¨ Build
              run: |
                  cd docs_headless
                  yarn build
                  touch dist/.nojekyll
                  cd ..

            - name: ğŸ“¡ Deploy GitHub pages
              run: yarn gh-pages --remote production -d docs_headless/dist -b ${{ vars.DEPLOY_BRANCH || 'gh-pages' }}
              env:
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
